### DISCUSSION TITLE
Video blurring/artifacts

### DISCUSSION THREAD

**Discussion by pdobrien3** [gtxaspec/wz_mini_hacks#574] [General]
I have a Wyze V3 on Wifi.  Using frigate for recording.  I have tried everything to stop the blurring / artifacts on the recorded video but cant figure it out.  I have heard that using RTSP over TCP fixes the issue.  Is this possible?  here are my settings:

```
RTSP_HI_RES_ENABLED="true"
RTSP_HI_RES_ENABLE_AUDIO="true"
RTSP_HI_RES_FPS="10"
RTSP_HI_RES_MAX_BITRATE="4096"
RTSP_HI_RES_TARGET_BITRATE="2048"
RTSP_HI_RES_ENC_PARAMETER="2"

RTSP_LOW_RES_ENABLED="true"
RTSP_LOW_RES_ENABLE_AUDIO="false"
RTSP_LOW_RES_FPS="5"
RTSP_LOW_RES_MAX_BITRATE="2048"
RTSP_LOW_RES_TARGET_BITRATE="1024"
RTSP_LOW_RES_ENC_PARAMETER="2"

```

```
  garage_camera: 
    ffmpeg:
      input_args: preset-rtsp-udp
      output_args:
        detect: -dn -an -f rawvideo -pix_fmt yuv420p
        record: -dn -f segment -segment_time 10 -segment_format h.264 -reset_timestamps 1 -strftime 1 -codec:v copy -codec:a aac -b:a 24k -ac 1 
      inputs:
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video2_unicast
          hwaccel_args: preset-intel-qsv-h264
          roles:
            - detect
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video1_unicast
          hwaccel_args: preset-intel-qsv-h264
          roles:
            - record
```

**Comment by bailout00** [comment]
+1 I'm seeing the same issue, only seems to happen on the v3, random glitches of 1/3 of the screen, or blocks across the whole thing for many frames. Seems like a compression/keyframe issue.

**Comment by pdobrien3** [comment]
> +1 I'm seeing the same issue, only seems to happen on the v3, random glitches of 1/3 of the screen, or blocks across the whole thing for many frames. Seems like a compression/keyframe issue.

I pretty much have just accepted it. Any chance you are using wz_mini with a wyze pan v1?  I have had one heck of a time with getting recordings on my pan to work in frigate.

**Comment by mach7** [comment]
I have also been having the same issues. But it doesn't happen on all of my V3s. The setup is the same on each camera too. So I'm not sure exactly what is causing it either.

**Comment by sjmellen** [comment]
Same issue here on V3's.  As @bailout00 noted, random glitches on lower 1/3 of the screen or whole screen for many frames.  Camera connected wirelessly.  Observed both streaming to VLC as well as streaming to a "picture glace card" in Home Assistant.
BTW - anyone know how to force TCP... don't see anything in the configuration files.

**Comment by mach7** [comment]
Any chance that those of you who are seeing the green glitchy video are also using frigate?
I'm getting the green glitch when I am viewing my cameras in a picture glance card from Home assistant with the source being my frigate video feed, at the same time it happens I'm watching on the wyze app and on VLC the only place I get anything other then clean video is viewing the video feed from frigate.

**Comment by IR2Lazy** [comment]
I have green, purple or just fuzzy (mostly bottom half) in Home Assistant using picture entity and Zoneminder. Saw it in MotionEye when testing also. Didn't see issue while using VLC.

Zoneminder wiki for WyzeCam mentions the use of LibVLC, but I never got that to work 

https://wiki.zoneminder.com/Wyze_Cam

Enable RTSP via Wyze app.

Note: RTSP is only available with special, non-standard firmware. See instructions here: https://support.wyzecam.com/hc/en-us/articles/360026245231-Wyze-Cam-RTSP

Use RTSP path provided by app in this format:

rtsp://[user]:[password]@[IP]/live

Regardless of app settings, capture settings are 1920x1080 at 32 bit colour. Do not use maximum FPS.

FFMPEG results in significant artifacts; use of LibVLC is recommended instead.

**Comment by clee604** [comment]
> Same issue here on V3's. As @bailout00 noted, random glitches on lower 1/3 of the screen or whole screen for many frames. Camera connected wirelessly. Observed both streaming to VLC as well as streaming to a "picture glace card" in Home Assistant. BTW - anyone know how to force TCP... don't see anything in the configuration files.

I believe TCP can be set on the client side; for me I 'force' TCP by using simple-rtsp-server to proxy the wyze RTSP feed using 'sourceProtocol: tcp' in the simple-rtsp-server config. This eliminated the artifacting for me.

**Comment by pdobrien3** [comment]
Ok, so this is not one of the default configuration settings for wz_mini_hacks. So, If you wouldn’t mind, could you please tell us how you are using tcp with wz_mini_hack video. Everything I have read has said that doing video over tcp fixes the issue. I just can’t figure out how to do it. Thanks in advance for any assistance.

**Comment by clee604** [comment]
I have some wyze cameras running wz_mini_hacks with RTSP enabled. Instead of connecting to cameras directly, I run a rtsp proxy using simple-rtsp-server on a linux host. In the simple-rtsp-server config where I reference the wyze RTSP feeds, I set the sourceProtocol to TCP. The end clients (ie. VLC, TinyCam), point to the rtsp proxy instead of the cameras directly.

I don't know about VLC, but I know TinyCam allows you to specify the protocol, and you can set it to be TCP there.

**Comment by pdobrien3** [comment]
Nice. I just spun up a container version. Was able to proxy my streams. Need to play with settings still. Thank you.

**Comment by pdobrien3** [comment]
@clee604 do you get a lot of packet loss in your simple-rtsp-server logs?  Still seeing the artifacts when going through simple-rtsp-server. I wonder if it is just packet loss due to a Wi-Fi connection.  Although like everyone else says, the stream is clear in VLC.

**Comment by clee604** [comment]
> @clee604 do you get a lot of packet loss in your simple-rtsp-server logs? Still seeing the artifacts when going through simple-rtsp-server. I wonder if it is just packet loss due to a Wi-Fi connection. Although like everyone else says, the stream is clear in VLC.

I got some RTP packet loss errors when I left it on the default (ie. using UDP) but after forcing TCP in the simple-rtsp-server yaml I haven't noticed any errors in the logs, though I haven't been monitoring them carefully since I haven't gotten the artifacts anymore

**Comment by pdobrien3** [comment]
So I think I finally fixed it by increasing the bitrate figures and lowering the frame rate to 15 fps.  Not using anything but wz_mini_hacks. 

Max bitrate=8192
Target bitrate=4096
Enc parameter=2
FPS=15

still early on but looks promising.

**Comment by mach7** [comment]
Can you tell me what your work flow is from the camera to when you view it?

**Comment by pdobrien3** [comment]
Wyze V3 with wz_mini to Frigate. After about 12 hours, here is where I am.  It is not fixed with the wz_mini config changes. I am all but positive it has to do with frame drops and where you are viewing the feed. I have a windows 10 desktop and a windows 11 desktop. When viewing frigate recording on the windows 11 desktop, I see the issue manifest in video artifacts. When I watch the frigate recorded video on the windows 10 desktop, I see the issue manifest with glitching video but no artifacts. The time stamp either hesitates or goes backwards sometimes. On both computers, when watching the live video with VLC, no artifacts but the live video pauses.  When being used to convert to TCP, simple-rtsp-server still reports frames being dropped. Both my wyze v3s are connecting via Wi-Fi.

**Comment by mach7** [comment]
> Wyze V3 with wz_mini to Frigate. After about 12 hours, here is where I am. It is not fixed with the wz_mini config changes. I am all but positive it has to do with frame drops and where you are viewing the feed. I have a windows 10 desktop and a windows 11 desktop. When viewing frigate recording on the windows 11 desktop, I see the issue manifest in video artifacts. When I watch the frigate recorded video on the windows 10 desktop, I see the issue manifest with glitching video but no artifacts. The time stamp either hesitates or goes backwards sometimes. On both computers, when watching the live video with VLC, no artifacts but the live video pauses. When being used to convert to TCP, simple-rtsp-server still reports frames being dropped. Both my wyze v3s are connecting via Wi-Fi.

That last comment you made about the wifi is one of the things I've been wondering about too. I have a mesh router system showing up tonight in hopes to clear up some wifi issues that I'm having in our home. When I was ordering it I was thinking about this thread and also wondered, what type of wifi system you had setup with your environment. Is it a standard router or are you also running a mesh system?

As for me it seems like I have a similar setup. I'll watch mine more closely and report on it when I start taking some notes on it as well. 

@gtxaspec - Do you have any input on this thread?

**Comment by pdobrien3** [comment]
I have a DIY mesh with asus routers and dd-wrt. I am 99% sure the issue is caused by frame drops. I have been able to get the frame drops to an acceptable level on one of my Wyze cameras but haven’t had a chance to verify the results.

**Comment by shehzman** [comment]
Just setup wz_mini_hacks on my v3 and am running Frigate and am also having these issues. Were you able to figure out a solution?

**Comment by pdobrien3** [comment]
Pretty sure it is a bandwidth issue. I gave up. Are you running them wireless?  I think I was able to improve it a little by keeping them on separate routers in my house. I also got the fastest sd card I could.

**Comment by shehzman** [comment]
I am running it wireless, but then I switched to the official RTSP firmware
and it worked near perfectly so I don’t think it’s a bandwidth issue for me

**Comment by pdobrien3** [comment]
So, I have 100% fixed the blurring/artifacts in frigate by using the restream:

```
go2rtc:
  streams:
    your_camera: 
      - "ffmpeg:rtsp://your_user:your_password@192.168.xx.xxx:8554/video1_unicast#video=h264#audio=aac"

```
Here is my camera setup in frigate:

```
  your_camera:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        detect: -dn -an -sn -f rawvideo -pix_fmt yuv420p
        record: -sn -dn -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -codec:v copy -codec:a aac -b:a 16k -ac 0
      inputs:
        - path: rtsp://your_user:your_password@192.168.xx.xxx:8554/video2_unicast
          input_args: preset-rtsp-udp
          roles:
            - detect
        - path: rtsp://localhost:8554/your_camera
          input_args: preset-rtsp-restream
          roles:
            - record
```
Here is my docker-compose

 ```
 frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256M"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /your/path/docker/frigate/config/config.yml:/config/config.yml:ro
      - /your/path/docker/frigate/data:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
    environment:
      FRIGATE_RTSP_PASSWORD: "your_password"
      PLUS_API_KEY: your_key
      LIBVA_DRIVER_NAME: i965

```

Still working through ffmpeg crashes in Frigate though.  Funny, I have two of the same Wyze cameras and only one seems to be crashing, although I have only been testing this setup today.  It is rock solid in record and mse playback though.

**Comment by pdobrien3** [comment]
keep getting this:

```
2023-05-16 20:32:18.808069842  [2023-05-16 20:32:18] watchdog.your_camera    ERROR   : No new recording segments were created for your_camera in the last 120s. restarting the ffmpeg record process...
2023-05-16 20:32:18.808452006  [2023-05-16 20:32:18] watchdog.your_camera    INFO    : Terminating the existing ffmpeg process...
2023-05-16 20:32:18.809152291  [2023-05-16 20:32:18] watchdog.your_camera    INFO    : Waiting for ffmpeg to exit gracefully...
```

**Comment by gtxaspec** [comment]
Try the new release with go2rtc.

**Reply by pdobrien3** [reply]
This has been flooding my Frigate logs on Frigate 0.13.0-0858859.  

```
2023-10-14 08:46:06.130153126  [h264 @ 0x7fd108006c80] error while decoding MB 117 59, bytestream -13
2023-10-14 08:47:16.138603725  [h264 @ 0x7fd10828f340] left block unavailable for requested intra mode
2023-10-14 08:47:16.138607367  [h264 @ 0x7fd10828f340] error while decoding MB 0 63, bytestream 11425
2023-10-14 08:48:36.139432029  [h264 @ 0x7fd108006c80] left block unavailable for requested intra mode
2023-10-14 08:48:36.139435400  [h264 @ 0x7fd108006c80] error while decoding MB 0 63, bytestream 3793
2023-10-14 08:48:46.162074680  [h264 @ 0x7fd108498400] error while decoding MB 13 67, bytestream -7
2023-10-14 08:48:56.153256085  [h264 @ 0x7fd108498400] left block unavailable for requested intra mode
2023-10-14 08:48:56.153260331  [h264 @ 0x7fd108498400] error while decoding MB 0 62, bytestream 8791
2023-10-14 08:50:16.151427297  [h264 @ 0x7fd108498400] error while decoding MB 111 65, bytestream -77
2023-10-14 08:50:26.141634032  [h264 @ 0x7fd108006c80] error while decoding MB 18 67, bytestream -35
2023-10-14 08:50:46.136050176  [h264 @ 0x7fd108498400] error while decoding MB 32 43, bytestream -12
2023-10-14 08:51:36.146492129  [h264 @ 0x7fd108498400] left block unavailable for requested intra mode
2023-10-14 08:51:36.146496364  [h264 @ 0x7fd108498400] error while decoding MB 0 65, bytestream 4595
2023-10-14 08:51:46.159474782  [h264 @ 0x7fd108498400] left block unavailable for requested intra4x4 mode -1
2023-10-14 08:51:46.159478192  [h264 @ 0x7fd108498400] error while decoding MB 0 65, bytestream 752
2023-10-14 08:52:46.148724433  [h264 @ 0x7fd108498400] error while decoding MB 100 60, bytestream -37
2023-10-14 08:53:06.153899965  [h264 @ 0x7fd108498400] error while decoding MB 74 64, bytestream -9
2023-10-14 08:53:16.131784989  [h264 @ 0x7fd108498400] error while decoding MB 118 66, bytestream -13
2023-10-14 08:53:36.162913765  [h264 @ 0x7fd108498400] error while decoding MB 105 64, bytestream -44
2023-10-14 08:54:06.140336081  [h264 @ 0x7fd108498400] error while decoding MB 115 66, bytestream -9
2023-10-14 08:54:36.140899449  [h264 @ 0x7fd108498400] error while decoding MB 102 64, bytestream -5
2023-10-14 08:55:06.142320154  [h264 @ 0x7fd108498400] error while decoding MB 99 64, bytestream -35
2023-10-14 08:55:16.128459699  [h264 @ 0x7fd108498400] error while decoding MB 118 67, bytestream -9
2023-10-14 08:55:26.124290120  [h264 @ 0x7fd1080ebb40] error while decoding MB 96 64, bytestream -27
2023-10-14 08:56:36.170941684  [h264 @ 0x7fd108498400] left block unavailable for requested intra4x4 mode -1
2023-10-14 08:56:36.170946305  [h264 @ 0x7fd108498400] error while decoding MB 0 63, bytestream 13209
2023-10-14 08:57:06.159152801  [h264 @ 0x7fd108498400] error while decoding MB 95 64, bytestream -37
2023-10-14 08:57:56.182725696  [h264 @ 0x7fd108498400] left block unavailable for requested intra mode
2023-10-14 08:57:56.182730587  [h264 @ 0x7fd108498400] error while decoding MB 0 64, bytestream 4148
2023-10-14 08:58:06.165321107  [h264 @ 0x7fd108498400] left block unavailable for requested intra mode
2023-10-14 08:58:06.165324263  [h264 @ 0x7fd108498400] error while decoding MB 0 65, bytestream 1292
2023-10-14 09:00:36.181288981  [h264 @ 0x7fd108498400] error while decoding MB 98 54, bytestream -15
```

If I hash out my wz_mini_hacks Wyze cameras the errors disappear.  Unknown if it is related to the new release with go2rtc or not.  I am not using gortc.  I worked through all the Frigate Camera config.yaml options on the Frigate side and was unable to fix it.  https://github.com/blakeblackshear/frigate/issues/7874

**Reply by gtxaspec** [reply]
As far as I know, v4l2rtspserver does not work well with frigate, it never has.  Try go2rtc

**Comment by pdobrien3** [comment]
Hmm...after running `upgrade-run.sh` I can see the video in frigate (haven't tried the go2rtc stream yet).  I can see the landing page for the camera but when I click any of the links, it times out.  I can't get to the config page.

update:  actually after hitting `f5` on the landing page, it is unreachable also.
update2; switched to the go2rtc stream.  Will see how it goes.  Initially, no audio with:

```
your_camera: 
  - "ffmpeg:rtsp://user:pass@192.168.xx.xxx:8554/video1_unicast#video=h264#audio=aac#hardware"
  - "ffmpeg:your_camera#audio=opus" # used for WebRTC Audio
```
update3: actually, audio works fine with mse but, using webrtc seems to crash frigate.

**Comment by cdennis12280** [comment]
This artifacts problem really does make our v3's less desirable... Does this also happen on poe/hardwired v3's?

**Reply by Bob-AOL** [reply]
No. It also doesn't happen on clean, well thought out wi-fi networks. Mesh is always a crap-shoot. Access points, extenders and bridges are much more predictable, robust (and configurable).

Seems to me like the common denominator here aside from v3s and wz_mini is Frigate. Way too many hoops to jump through there on a good day, let alone a challenging one. You couldn't pay me to put all my eggs in that basket.

VLC doesn't always provide accurate technical assessments (or performance) either.

But if it weren't fun! LOL

Cheers.

**Comment by pdobrien3** [comment]
So I have really been able to clean up my frigate streams.  I had to upgrade to the latest wz_mini_hacks version that uses go2rtc and I am on the current frigate beta.  Not sure if being on the frigate beta matters though.  My streams are flawless except for some minor audio sync (one camera is more out of sync than the other) and I still get ffmpeg crashes but they aren't as regular and seem to be related to connection issues only.  I haven't figured out why one camera works with `#video=copy#video=h264` and the other one only works with `#video=h264`.  They will both work with `#video=h264` but adding the `#video=copy` to the one seems to make the live stream start quicker.  The live stream won't start on the one if it has `#video=copy#video=h264`.  Here is my frigate config:

```
go2rtc:
  streams:
    1_camera:
      - "ffmpeg:rtsp://user:password@192.168.xx.xxx:8554/video1_unicast#video=copy#video=h264#audio=copy#audio=aac"
    2_room_camera: 
      - "ffmpeg:rtsp://user:pass@192.168.xx.xxx:8554/video1_unicast#video=h264#audio=copy#audio=aac"
```

Here is my config.yaml for the cameras.  They are both the same:

```
  1_camera:
    ffmpeg:
      hwaccel_args: preset-vaapi
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://user:pass@192.168.xx.xxx:8554/video2_unicast
          input_args: preset-rtsp-udp
          roles:
            - detect
        - path: rtsp://localhost:8554/1_camera
          input_args: preset-rtsp-restream-low-latency
          roles:
            - record            
```
Would be interested in others results with this config.
