### DISCUSSION TITLE
use go2rtc stream from  "wz_mini_hacks" in frigate

### DISCUSSION THREAD

**Discussion by johnvprcam24573455623** [gtxaspec/wz_mini_hacks#584] [General]
I am trying to use the go2rtc stream from  "wz_mini_hacks" into frigate, however I am not sure that this is the right way of doing it

Frigagte config.yml
```
   wyze_cam_v3:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://10.10.40.218:8554/1080p?mp4
          roles:
            - record
        - path: rtsp://10.10.40.218:8554/360p?mp4   
          roles:
            - detect  
```

http://10.10.40.218:1984/
![image](https://github.com/gtxaspec/wz_mini_hacks/assets/88012789/600de7b3-9677-4508-9873-c13cc84179d2)

![image](https://github.com/gtxaspec/wz_mini_hacks/assets/88012789/5b57184e-f1fa-475f-872e-611ce798a7f7)
